package pantallas.ingredientes;

import DTOs.CRUDIngredientes.DetallesIngredienteViejoDTO;
import control.ControlNavegacion;



/**
 *
 * @author norma
 */
public class PantallaEditarDetallesIngrediente extends javax.swing.JFrame {

    DetallesIngredienteViejoDTO ingrediente;
    DetallesIngredienteViejoDTO ingredienteEditado;

    public PantallaEditarDetallesIngrediente(DetallesIngredienteViejoDTO ingrediente) {
        initComponents();
        this.ingrediente = ingrediente;
        this.ingredienteEditado = new DetallesIngredienteViejoDTO(ingrediente.getId(),ingrediente.getNombre(), ingrediente.getCantidadDisponible(), ingrediente.getCantidadMinima(), ingrediente.getUnidadMedida(), ingrediente.getNivelStock(), ingrediente.getIdProveedor());
        cargarNombreIngrediente();
        aplicarListeners();
    }

    public void cargarNombreIngrediente() {
        txtNombre.setText(ingredienteEditado.getNombre());
    }

    private void aplicarListeners() {
        txtNombre.getDocument().addDocumentListener(new javax.swing.event.DocumentListener() {
            @Override
            public void insertUpdate(javax.swing.event.DocumentEvent e) {
                editarNombre();
            }

            @Override
            public void removeUpdate(javax.swing.event.DocumentEvent e) {
                editarNombre();
            }

            @Override
            public void changedUpdate(javax.swing.event.DocumentEvent e) {
                editarNombre();
            }

            private void editarNombre() {
                ingredienteEditado.setNombre(txtNombre.getText());
                //validaciones de nombre ya exisite y caracteres maximo
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitulo = new javax.swing.JLabel();
        sepArriba = new javax.swing.JSeparator();
        lblNombreIngrediente = new javax.swing.JLabel();
        lblUnidadMedida = new javax.swing.JLabel();
        lblCantidadDisponible = new javax.swing.JLabel();
        lblCantidadMinima = new javax.swing.JLabel();
        lblEstado = new javax.swing.JLabel();
        lblProveedor = new javax.swing.JLabel();
        btnVolverAtras = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        txtUnidadMedida = new javax.swing.JLabel();
        txtCantidadDisponible = new javax.swing.JLabel();
        txtCantidadMinima = new javax.swing.JLabel();
        txtEstado = new javax.swing.JLabel();
        txtProveedor = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTitulo.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lblTitulo.setText("Editar detalles de ingrediente");
        lblTitulo.setToolTipText("");

        lblNombreIngrediente.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblNombreIngrediente.setText("Nombre");

        lblUnidadMedida.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblUnidadMedida.setText("Unidad de medida");

        lblCantidadDisponible.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblCantidadDisponible.setText("Cantidad disponible");

        lblCantidadMinima.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblCantidadMinima.setText("Cantidad mínima");

        lblEstado.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblEstado.setText("Estado");

        lblProveedor.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblProveedor.setText("Proveedor");

        btnVolverAtras.setBackground(new java.awt.Color(255, 204, 0));
        btnVolverAtras.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnVolverAtras.setText("<---");
        btnVolverAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverAtrasActionPerformed(evt);
            }
        });

        btnGuardar.setBackground(new java.awt.Color(255, 204, 0));
        btnGuardar.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        txtUnidadMedida.setBackground(new java.awt.Color(204, 204, 204));
        txtUnidadMedida.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtUnidadMedida.setText("unidad medida");

        txtCantidadDisponible.setBackground(new java.awt.Color(204, 204, 204));
        txtCantidadDisponible.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtCantidadDisponible.setText("cantidad disponible");

        txtCantidadMinima.setBackground(new java.awt.Color(204, 204, 204));
        txtCantidadMinima.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtCantidadMinima.setText("cantidad mínima");

        txtEstado.setBackground(new java.awt.Color(204, 204, 204));
        txtEstado.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtEstado.setText("estado");

        txtProveedor.setBackground(new java.awt.Color(204, 204, 204));
        txtProveedor.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtProveedor.setText("proveedor");

        txtNombre.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtNombre.setText("nombre ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sepArriba, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 507, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(45, 45, 45)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblCantidadMinima, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtCantidadMinima, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblNombreIngrediente, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(60, 60, 60)
                                        .addComponent(lblUnidadMedida, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtUnidadMedida, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblCantidadDisponible, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtCantidadDisponible, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnVolverAtras, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(460, 460, 460)
                        .addComponent(btnGuardar, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sepArriba, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombreIngrediente)
                    .addComponent(lblUnidadMedida)
                    .addComponent(txtUnidadMedida)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCantidadDisponible)
                    .addComponent(txtCantidadDisponible))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCantidadMinima)
                    .addComponent(txtCantidadMinima))
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEstado)
                    .addComponent(txtEstado))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblProveedor)
                    .addComponent(txtProveedor))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 95, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(btnVolverAtras, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        //guardar cambios
        ControlNavegacion.mostrarPantallaVerDetallesIngrediente(ingrediente.getId());
        this.dispose();
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnVolverAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverAtrasActionPerformed
        ControlNavegacion.mostrarPantallaVerDetallesIngrediente(ingrediente.getId());
        this.dispose();
    }//GEN-LAST:event_btnVolverAtrasActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnVolverAtras;
    private javax.swing.JLabel lblCantidadDisponible;
    private javax.swing.JLabel lblCantidadMinima;
    private javax.swing.JLabel lblEstado;
    private javax.swing.JLabel lblNombreIngrediente;
    private javax.swing.JLabel lblProveedor;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblUnidadMedida;
    private javax.swing.JSeparator sepArriba;
    private javax.swing.JLabel txtCantidadDisponible;
    private javax.swing.JLabel txtCantidadMinima;
    private javax.swing.JLabel txtEstado;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JLabel txtProveedor;
    private javax.swing.JLabel txtUnidadMedida;
    // End of variables declaration//GEN-END:variables
}
