package pantallas.ingredientes;

import DTOs.CRUDIngredientes.IngredienteNuevoDTO;
import DTOs.CRUDIngredientes.ProveedorViejoDTO;
import DTOs.CRUDIngredientes.UnidadMedida;
import control.ControlNavegacion;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;

/**
 *
 * @author norma
 */
public class PantallaAgregarIngrediente extends javax.swing.JFrame {

    IngredienteNuevoDTO ingredienteNuevo;

    public PantallaAgregarIngrediente() {
        initComponents();
        cargarComboBox();
        listenerVerificarCampos();
        btnGuardarIngrediente.setEnabled(false);
    }

    private void cargarComboBox() {
        comboBoxUnidadMedida.removeAllItems();

        for (UnidadMedida unidad : UnidadMedida.values()) {
            comboBoxUnidadMedida.addItem(unidad.toString());
        }

        comboBoxProveedor.removeAllItems();

        List<ProveedorViejoDTO> proveedores = ControlNavegacion.obtenerProveedores();
        for (ProveedorViejoDTO proveedor : proveedores) {
            comboBoxProveedor.addItem(proveedor);
        }
    }

    private void registrarInformacionIngrediente() {
        String nombre = txtNombre.getText().trim().toLowerCase();
        String cantidadDisponibleStr = txtCantidadDisponible.getText().trim();
        String cantidadMinimaStr = txtCantidadMinima.getText().trim();
        String unidadMedidaStr = (String) comboBoxUnidadMedida.getSelectedItem();
        ProveedorViejoDTO proveedor = (ProveedorViejoDTO) comboBoxProveedor.getSelectedItem();

        UnidadMedida unidadMedida = UnidadMedida.valueOf(unidadMedidaStr.toUpperCase());

        Double cantidadDisponible = Double.parseDouble(cantidadDisponibleStr);
        Double cantidadMinima = Double.parseDouble(cantidadMinimaStr);

        ingredienteNuevo = new IngredienteNuevoDTO();
        ingredienteNuevo.setNombre(nombre);
        ingredienteNuevo.setCantidadDisponible(cantidadDisponible);
        ingredienteNuevo.setCantidadMinima(cantidadMinima);
        ingredienteNuevo.setUnidadMedida(unidadMedida);
        ingredienteNuevo.setIdProveedor(proveedor.getId());

        agregarNuevoIngrediente();
    }

    public void agregarNuevoIngrediente() {
        ControlNavegacion.agregarIngrediente(ingredienteNuevo);
        ControlNavegacion.mostrarPantallaListaIngredientes();
        this.dispose();
    }

    private void listenerVerificarCampos() {
        txtNombre.getDocument().addDocumentListener(new DocumentListener() {
            @Override
            public void insertUpdate(DocumentEvent e) {
                verificarCampos();
            }

            @Override
            public void removeUpdate(DocumentEvent e) {
                verificarCampos();
            }

            @Override
            public void changedUpdate(DocumentEvent e) {
                verificarCampos();
            }
        });

        txtCantidadDisponible.getDocument().addDocumentListener(new DocumentListener() {
            @Override
            public void insertUpdate(DocumentEvent e) {
                verificarCampos();
            }

            @Override
            public void removeUpdate(DocumentEvent e) {
                verificarCampos();
            }

            @Override
            public void changedUpdate(DocumentEvent e) {
                verificarCampos();
            }
        });

        comboBoxUnidadMedida.addActionListener(e -> verificarCampos());
        comboBoxProveedor.addActionListener(e -> verificarCampos());
    }

    private void verificarCampos() {
        String nombre = txtNombre.getText().trim();
        String unidadMedidaStr = (String) comboBoxUnidadMedida.getSelectedItem();
        ProveedorViejoDTO proveedorSeleccionado = (ProveedorViejoDTO) comboBoxProveedor.getSelectedItem();
        String cantidadDisponibleStr = txtCantidadDisponible.getText().trim();

        if (!nombre.isEmpty() && !cantidadDisponibleStr.isEmpty() && !unidadMedidaStr.isEmpty()) {
            btnGuardarIngrediente.setEnabled(true);
        } else {
            btnGuardarIngrediente.setEnabled(false);
        }

        //validar caracteres maximo, cantidad disponible baja, alta o letras
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitulo = new javax.swing.JLabel();
        sepArriba = new javax.swing.JSeparator();
        btnVolverAtras = new javax.swing.JButton();
        btnGuardarIngrediente = new javax.swing.JButton();
        lblUnidadMedida = new javax.swing.JLabel();
        txtCantidadDisponible = new javax.swing.JTextField();
        lblNombreIngrediente = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        lblCantidadDisponible = new javax.swing.JLabel();
        lblProveedor = new javax.swing.JLabel();
        comboBoxUnidadMedida = new javax.swing.JComboBox<>();
        comboBoxProveedor = new javax.swing.JComboBox<>();
        lblCantidadMinima = new javax.swing.JLabel();
        txtCantidadMinima = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTitulo.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lblTitulo.setText("Agregar ingrediente");
        lblTitulo.setToolTipText("");

        btnVolverAtras.setBackground(new java.awt.Color(255, 204, 0));
        btnVolverAtras.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnVolverAtras.setText("<---");
        btnVolverAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverAtrasActionPerformed(evt);
            }
        });

        btnGuardarIngrediente.setBackground(new java.awt.Color(255, 204, 0));
        btnGuardarIngrediente.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnGuardarIngrediente.setText("Guardar ingrediente");
        btnGuardarIngrediente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarIngredienteActionPerformed(evt);
            }
        });

        lblUnidadMedida.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblUnidadMedida.setText("Unidad de medida");

        txtCantidadDisponible.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        lblNombreIngrediente.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblNombreIngrediente.setText("Nombre de ingrediente");

        txtNombre.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        lblCantidadDisponible.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblCantidadDisponible.setText("Cantidad disponible");

        lblProveedor.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblProveedor.setText("Proveedor");

        comboBoxUnidadMedida.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        comboBoxUnidadMedida.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        comboBoxProveedor.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        lblCantidadMinima.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblCantidadMinima.setText("Cantidad mínima");

        txtCantidadMinima.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(sepArriba, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 862, Short.MAX_VALUE)
                            .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 507, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btnVolverAtras, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(460, 460, 460)
                                .addComponent(btnGuardarIngrediente, javax.swing.GroupLayout.DEFAULT_SIZE, 262, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txtCantidadDisponible, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblNombreIngrediente, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtNombre)
                                .addComponent(txtCantidadMinima, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblCantidadMinima, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblCantidadDisponible, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(124, 124, 124)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblUnidadMedida, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(comboBoxUnidadMedida, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(comboBoxProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sepArriba, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombreIngrediente)
                    .addComponent(lblUnidadMedida))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboBoxUnidadMedida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCantidadDisponible)
                    .addComponent(lblProveedor))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCantidadDisponible, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboBoxProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addComponent(lblCantidadMinima)
                .addGap(28, 28, 28)
                .addComponent(txtCantidadMinima, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 77, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(btnVolverAtras, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnGuardarIngrediente, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVolverAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverAtrasActionPerformed
        ControlNavegacion.mostrarPantallaListaIngredientes();
        this.dispose();
    }//GEN-LAST:event_btnVolverAtrasActionPerformed

    private void btnGuardarIngredienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarIngredienteActionPerformed
        registrarInformacionIngrediente();
    }//GEN-LAST:event_btnGuardarIngredienteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardarIngrediente;
    private javax.swing.JButton btnVolverAtras;
    private javax.swing.JComboBox<ProveedorViejoDTO> comboBoxProveedor;
    private javax.swing.JComboBox<String> comboBoxUnidadMedida;
    private javax.swing.JLabel lblCantidadDisponible;
    private javax.swing.JLabel lblCantidadMinima;
    private javax.swing.JLabel lblNombreIngrediente;
    private javax.swing.JLabel lblProveedor;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblUnidadMedida;
    private javax.swing.JSeparator sepArriba;
    private javax.swing.JTextField txtCantidadDisponible;
    private javax.swing.JTextField txtCantidadMinima;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
