/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package pantallas.cubiculos;

import pantallas.*;
import DTOs.ProductoPedidoDTO;
import java.awt.event.ActionListener;

/**
 * Clase que representa un panel para mostrar los detalles de un producto en un
 * pedido como el producto, tamaño, sabor, topping, cantidad y precio. Además,
 * permite la edición de la cantidad y la cancelación de un pedido de producto.
 *
 * @author norma
 */
public class PanelReservacionHistorial extends javax.swing.JPanel {

    private ProductoPedidoDTO productoPedido;

    /**
     * Crea un nuevo panel para mostrar la información de un producto pedido en
     * el pedido.
     *
     * @param productoPedido El objeto que contiene la información del producto
     * y su pedido.
     */
    public PanelReservacionHistorial(ProductoPedidoDTO productoPedido) {
        initComponents();
        this.productoPedido = productoPedido;
        this.lblNombreCliente.setText(productoPedido.getProducto().getNombre());
        this.lblTopping.setText("");
        if (productoPedido.getTopping() != null) {
            this.lblTopping.setText(productoPedido.getTopping().getNombre());
        }
        double costo = productoPedido.getCosto();
        this.lblFechaTxt.setText(String.format("%.2f", costo));
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNombreCliente = new javax.swing.JLabel();
        lblFechaTxt = new javax.swing.JLabel();
        lblTopping = new javax.swing.JLabel();
        btnDetalle = new javax.swing.JButton();
        lblHoraInicio = new javax.swing.JLabel();
        lblHoraTxt = new javax.swing.JLabel();
        lblFecha = new javax.swing.JLabel();
        lblFechaSeparador = new javax.swing.JLabel();
        lblHoraFin = new javax.swing.JLabel();
        lblNombreCubiculo = new javax.swing.JLabel();
        lblEstado = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblNombreCliente.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblNombreCliente.setText("Nombre");

        lblFechaTxt.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblFechaTxt.setText("Fecha:");

        lblTopping.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        btnDetalle.setBackground(new java.awt.Color(153, 153, 153));
        btnDetalle.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnDetalle.setForeground(new java.awt.Color(255, 255, 255));
        btnDetalle.setText("Ver Detalle");
        btnDetalle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDetalleActionPerformed(evt);
            }
        });

        lblHoraInicio.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblHoraInicio.setText("HoraInicio");

        lblHoraTxt.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblHoraTxt.setText("Hora:");

        lblFecha.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblFecha.setText("00/00/0000");

        lblFechaSeparador.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblFechaSeparador.setText("-");

        lblHoraFin.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblHoraFin.setText("HoraFin");

        lblNombreCubiculo.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblNombreCubiculo.setText("Cubiculo A");

        lblEstado.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblEstado.setText("Estado");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblFechaTxt)
                                .addGap(18, 18, 18)
                                .addComponent(lblFecha))
                            .addComponent(lblTopping)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblHoraTxt)
                                .addGap(18, 18, 18)
                                .addComponent(lblHoraInicio)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblFechaSeparador)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblHoraFin)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 192, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblNombreCliente)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 149, Short.MAX_VALUE)
                        .addComponent(lblNombreCubiculo)
                        .addGap(115, 115, 115)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnDetalle)
                    .addComponent(lblEstado))
                .addGap(32, 32, 32))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblNombreCliente)
                            .addComponent(lblNombreCubiculo)
                            .addComponent(lblEstado))
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblFechaTxt)
                            .addComponent(lblFecha))
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblHoraTxt)
                            .addComponent(lblHoraInicio)
                            .addComponent(lblFechaSeparador)
                            .addComponent(lblHoraFin))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblTopping))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(94, 94, 94)
                        .addComponent(btnDetalle)))
                .addContainerGap(28, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnDetalleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDetalleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDetalleActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDetalle;
    private javax.swing.JLabel lblEstado;
    private javax.swing.JLabel lblFecha;
    private javax.swing.JLabel lblFechaSeparador;
    private javax.swing.JLabel lblFechaTxt;
    private javax.swing.JLabel lblHoraFin;
    private javax.swing.JLabel lblHoraInicio;
    private javax.swing.JLabel lblHoraTxt;
    private javax.swing.JLabel lblNombreCliente;
    private javax.swing.JLabel lblNombreCubiculo;
    private javax.swing.JLabel lblTopping;
    // End of variables declaration//GEN-END:variables
}
