/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package pantallas.cubiculos;

import pantallas.*;
import DTOs.ProductoPedidoDTO;
import DTOs.cubiculos.ReservacionDTOMostrar;
import java.awt.event.ActionListener;

/**
 * Clase que representa un panel para mostrar los detalles de una reservacion
 * como el numero, nombre, cubiculo, estado, fecha, hora inicio y fin. Además,
 * permite iniciar o cancelar la reservacion.
 *
 * @author rodri
 */
public class PanelReservacion extends javax.swing.JPanel {

    ReservacionDTOMostrar dtoMostrar;
    
    /**
     * Crea un nuevo panel para mostrar la información de una reservacion
     *
     * @param reservacionMostrar El objeto que contiene la información de la reservacion
     * 
     */
    public PanelReservacion(ReservacionDTOMostrar reservacionMostrar) {
        initComponents();
        this.dtoMostrar = reservacionMostrar;
        
        this.lblNumReservacion.setText(String.valueOf("N#: " + dtoMostrar.getNumReservacion()));
        this.lblNombre.setText(dtoMostrar.getNombre());
        this.lblNombreCubiculo.setText(dtoMostrar.getNombreCubiculo());
        this.lblEstado.setText(dtoMostrar.getEstado());
        this.lblFecha.setText(dtoMostrar.getFechaInicio().toString());
        this.lblHoraInicio.setText(dtoMostrar.getHoraInicio().toString());
        this.lblHoraFin.setText(dtoMostrar.getHoraFin().toString());
    }
    
    public ReservacionDTOMostrar getProductoPedido() {
        return this.dtoMostrar;
    }
    
    /**
     * Establece el escuchador de acción para el botón de cancelar.
     *
     * @param listener El escuchador de acción para el botón de cancelar.
     */
    public void setCancelarActionListener(ActionListener listener) {
        this.btnCancelar.addActionListener(listener);
    }
    
    /**
     * Establece el escuchador de acción para el botón de iniciar.
     *
     * @param listener El escuchador de acción para el botón de iniciar.
     */
    public void setIniciarActionListener(ActionListener listener) {
        this.btnIniciar.addActionListener(listener);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNombre = new javax.swing.JLabel();
        lblFechaTxt = new javax.swing.JLabel();
        btnIniciar = new javax.swing.JButton();
        lblTopping = new javax.swing.JLabel();
        btnCancelar = new javax.swing.JButton();
        lblHoraInicio = new javax.swing.JLabel();
        lblHoraTxt = new javax.swing.JLabel();
        lblFecha = new javax.swing.JLabel();
        lblFechaSeparador = new javax.swing.JLabel();
        lblHoraFin = new javax.swing.JLabel();
        lblNombreCubiculo = new javax.swing.JLabel();
        lblEstado = new javax.swing.JLabel();
        lblNumReservacion = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblNombre.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblNombre.setText("Nombre");

        lblFechaTxt.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblFechaTxt.setText("Fecha:");

        btnIniciar.setBackground(new java.awt.Color(153, 153, 153));
        btnIniciar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnIniciar.setForeground(new java.awt.Color(255, 255, 255));
        btnIniciar.setText("Iniciar");
        btnIniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIniciarActionPerformed(evt);
            }
        });

        lblTopping.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        btnCancelar.setBackground(new java.awt.Color(153, 153, 153));
        btnCancelar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnCancelar.setForeground(new java.awt.Color(255, 255, 255));
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        lblHoraInicio.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblHoraInicio.setText("HoraInicio");

        lblHoraTxt.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblHoraTxt.setText("Hora:");

        lblFecha.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblFecha.setText("00/00/0000");

        lblFechaSeparador.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblFechaSeparador.setText("-");

        lblHoraFin.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblHoraFin.setText("HoraFin");

        lblNombreCubiculo.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblNombreCubiculo.setText("Cubiculo A");

        lblEstado.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblEstado.setText("Estado");

        lblNumReservacion.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblNumReservacion.setText("00");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblTopping)
                        .addContainerGap(631, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblHoraTxt)
                                        .addGap(18, 18, 18)
                                        .addComponent(lblHoraInicio)
                                        .addGap(32, 32, 32)
                                        .addComponent(lblFechaSeparador)
                                        .addGap(49, 49, 49)
                                        .addComponent(lblHoraFin))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(lblNumReservacion)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(lblNombre))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(lblFechaTxt)
                                            .addGap(18, 18, 18)
                                            .addComponent(lblFecha))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 129, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(lblNombreCubiculo)
                                .addGap(71, 71, 71)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblEstado)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(btnCancelar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnIniciar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(46, 46, 46))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblFechaTxt)
                            .addComponent(lblFecha))
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblHoraTxt)
                            .addComponent(lblHoraInicio)
                            .addComponent(lblFechaSeparador)
                            .addComponent(lblHoraFin)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lblEstado)
                                .addComponent(lblNombreCubiculo)
                                .addComponent(lblNombre)
                                .addComponent(lblNumReservacion))
                            .addGap(140, 140, 140))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(btnIniciar)
                            .addGap(18, 18, 18)
                            .addComponent(btnCancelar))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTopping)
                .addContainerGap(28, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnIniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniciarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnIniciarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnIniciar;
    private javax.swing.JLabel lblEstado;
    private javax.swing.JLabel lblFecha;
    private javax.swing.JLabel lblFechaSeparador;
    private javax.swing.JLabel lblFechaTxt;
    private javax.swing.JLabel lblHoraFin;
    private javax.swing.JLabel lblHoraInicio;
    private javax.swing.JLabel lblHoraTxt;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblNombreCubiculo;
    private javax.swing.JLabel lblNumReservacion;
    private javax.swing.JLabel lblTopping;
    // End of variables declaration//GEN-END:variables
}
