/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pantallas.cubiculos;

import pantallas.*;
import DTOs.PedidoDTO;
import control.ControlNavegacion;
import DTOs.ProductoPedidoDTO;
import DTOs.cubiculos.ReservacionDTOMostrar;
import control.Modo;
import exception.GestionException;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.List;
import java.util.Timer;
import java.util.TimerTask;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BoxLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 * Clase que representa la pantalla de total desglosado de un pedido.
 *
 * @author norma
 */
public class PantallaVerReservaciones extends javax.swing.JFrame {

    private final int MOVIMIENTO_SCROLL_MOUSE = 15;

    /**
     * Constructor de la clase PantallaVerReservaciones. Inicializa los componentes de la
     * interfaz y ajusta el tamaño de la ventana.
     *
     * Llama a los métodos para cargar las reservaciones pendientes e iniciadas y ajustar el
     * scroll.
     */
    public PantallaVerReservaciones() {
        initComponents();
        setSize(1000, 800);
        cargarPanelesReservaciones();
        ajustarScroll();
    }

    /**
     * Ajusta el comportamiento del scroll vertical de las reservaciones en el
     * panel.
     */
    private void ajustarScroll() {
        pnlVerReservaciones.getVerticalScrollBar().setUnitIncrement(MOVIMIENTO_SCROLL_MOUSE);
    }

    /**
     * Carga los paneles de las reservaciones
     */
    public void cargarPanelesReservaciones() {
        int posicionScroll = pnlVerReservaciones.getVerticalScrollBar().getValue();
        JPanel contenedorPanelesReservaciones = obtenerPanelesReservaciones();
        this.pnlVerReservaciones.setViewportView(contenedorPanelesReservaciones);
        pnlVerReservaciones.getVerticalScrollBar().setValue(posicionScroll);
    }

    /**
     * Obtiene un panel que contiene todos los datos de las reservaciones.
     *
     * @return JPanel que contiene los datos de las reservaciones.
     */
    private JPanel obtenerPanelesReservaciones() {
        
        List<ReservacionDTOMostrar> listaVerReservaciones = ControlNavegacion.cargarReservacionesPendientes(null, null);

        JPanel contenedorPanelesVerReservaciones = new JPanel();
        contenedorPanelesVerReservaciones.setLayout(new BoxLayout(contenedorPanelesVerReservaciones, BoxLayout.Y_AXIS));

        for (ReservacionDTOMostrar reservacion : listaVerReservaciones) {
            PanelReservacion panelReservacion = new PanelReservacion(reservacion);
            configurarPanelProducto(panelReservacion);
            contenedorPanelesVerReservaciones.add(panelReservacion);
        }

        return contenedorPanelesVerReservaciones;
    }

    /**
     * Configura los listeners para cada panel de reservacion (iniciar, cancelar).
     *
     * @param panelRes El panel de reservacion a configurar.
     */
    private void configurarPanelProducto(PanelReservacion panelRes) {
        panelRes.setCancelarActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
            }
        });
        panelRes.setIniciarActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
            }
        });
        

    }

    /**
     * Cancela un producto específico del pedido y actualiza la interfaz.
     *
     * @param productoPedido El producto a cancelar.
     */
    private void cancelarProductoPedido(ProductoPedidoDTO productoPedido) {
        int opc = JOptionPane.showConfirmDialog(
                this,
                "¿Deseas cancelar el producto pedido?",
                "Confirmar cancelación",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE
        );

        if (opc == JOptionPane.YES_OPTION) {
            ControlNavegacion.cancelarProductoPedido(productoPedido);

            ControlNavegacion.mostrarPantallaProductoPedidoCancelado(this);

            cargarPanelesReservaciones();
        }
    }



    /**
     * Thte javax.swing.JButton btnTarjeta; private javax.swing.JLabel lblSigno;
     * private javax.swing.JLabel lblTotal; private javax.swing.JLabel
     * lblTotalTotal; private javax.swing.JScrollPane pnlProductosPedidos; //
     * End of variables declaration } is method is called from within the
     * constructor to initialize the form. WARNING: Do NOT modify this code. The
     * content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlVerReservaciones = new javax.swing.JScrollPane();
        btnVolver = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabelTitulo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnVolver.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        btnVolver.setText("<--");
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });

        jLabelTitulo.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jLabelTitulo.setText("Ver Reservaciones");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(104, Short.MAX_VALUE)
                .addComponent(pnlVerReservaciones, javax.swing.GroupLayout.PREFERRED_SIZE, 822, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(98, 98, 98))
            .addComponent(jSeparator1)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jLabelTitulo)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(34, Short.MAX_VALUE)
                .addComponent(jLabelTitulo)
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pnlVerReservaciones, javax.swing.GroupLayout.PREFERRED_SIZE, 545, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Maneja el evento cuando se hace clic en el botón de pago con "Tarjeta".
     * Si el pedido está vacío, muestra un mensaje de error. Si hay productos,
     * navega a la pantalla de pago con tarjeta.
     *
     * @param evt el evento generado al hacer clic en el botón de pago con
     * "Tarjeta"
     */
    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        PedidoDTO pedido = ControlNavegacion.getPedido();
        List<ProductoPedidoDTO> listaProductosPedidos = pedido.getPedido();
        if (listaProductosPedidos.isEmpty()) {
            JOptionPane.showMessageDialog(null, "El pedido está vacío", "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            ControlNavegacion.mostrarPantallaPagoTarjeta();
            this.dispose();
        }
    }//GEN-LAST:event_btnVolverActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnVolver;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JScrollPane pnlVerReservaciones;
    // End of variables declaration//GEN-END:variables
}
