/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pantallas.cubiculos;

import DTOs.cubiculos.ReagendaDTO;
import control.ControlNavegacion;
import java.time.LocalDate;
import java.time.LocalTime;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author rodri
 */
public class PantallaReagendar extends javax.swing.JFrame {

    ReagendaDTO reagendaDTO;

    /**
     * Creates new form PantallaReagendar
     */
    public PantallaReagendar() {
        initComponents();
        cargarComboBox();
    }

    private void cargarComboBox() {
        jComboBox1.removeAllItems();

        List<String> listaCubiculos = ControlNavegacion.obtenerCubiculos();
        for (String cubiculo : listaCubiculos) {
            jComboBox1.addItem(cubiculo);
        }
    }

    public void crearReagenda() {
        if (jTextFieldNumReservacion.getText().isEmpty() || jTextFieldNumReservacion.getText().isBlank() || jTextFieldMotivo.getText().isEmpty()
                || jTextFieldMotivo.getText().isBlank() || jComboBox1.getSelectedItem() == null || fechaPicker.getDate() == null
                || horaInicioPicker.getTime() == null) {
            JOptionPane.showMessageDialog(this, "Todos los campos son obligatorios.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        String numReservacion = jTextFieldNumReservacion.getText();
        LocalDate fechaNueva = fechaPicker.getDate();
        LocalTime horaInicio = horaInicioPicker.getTime();
        String motivo = jTextFieldMotivo.getText();
        String numCubiculo = (String) jComboBox1.getSelectedItem();

        reagendaDTO = new ReagendaDTO();
        reagendaDTO.setNumReservacion(numReservacion);
        reagendaDTO.setFechaNueva(fechaNueva);
        reagendaDTO.setHoraInicio(horaInicio);
        reagendaDTO.setMotivo(motivo);
        reagendaDTO.setNombreCubiculo(numCubiculo);
    }

    public void guardarReagenda() {
        crearReagenda();
        if (reagendaDTO != null) {
            LocalTime horaFin = ControlNavegacion.setReagendaNueva(reagendaDTO);
            if (horaFin != null) {
                ControlNavegacion.realizarReagenda(reagendaDTO,horaFin);
                ControlNavegacion.mostrarPantallaReservacionExitosa();
                this.dispose();
            } else {
                JOptionPane.showMessageDialog(this, "No se puedo realizar la reagenda.", "Error", JOptionPane.ERROR_MESSAGE);
            }

            
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        lblTitulo = new javax.swing.JLabel();
        btnVolver = new javax.swing.JButton();
        btnReagendar = new javax.swing.JButton();
        horaInicioPicker = new com.github.lgooddatepicker.components.TimePicker();
        fechaPicker = new com.github.lgooddatepicker.components.DatePicker();
        jLabelFecha = new javax.swing.JLabel();
        jLabelHoraInicio = new javax.swing.JLabel();
        jTextFieldMotivo = new javax.swing.JTextField();
        jLabelMotivo = new javax.swing.JLabel();
        jLabelCubiculo = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jSeparator3 = new javax.swing.JSeparator();
        jLabelNumReservacion = new javax.swing.JLabel();
        jTextFieldNumReservacion = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTitulo.setText("Reagendar Cubiculo");
        lblTitulo.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N

        btnVolver.setText("Volver");
        btnVolver.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnVolver.setMaximumSize(new java.awt.Dimension(120, 70));
        btnVolver.setMinimumSize(new java.awt.Dimension(120, 70));
        btnVolver.setPreferredSize(new java.awt.Dimension(120, 70));
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });

        btnReagendar.setText("Reagendar");
        btnReagendar.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnReagendar.setMaximumSize(new java.awt.Dimension(120, 70));
        btnReagendar.setMinimumSize(new java.awt.Dimension(120, 70));
        btnReagendar.setPreferredSize(new java.awt.Dimension(120, 70));
        btnReagendar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReagendarActionPerformed(evt);
            }
        });

        horaInicioPicker.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N

        fechaPicker.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N

        jLabelFecha.setText("Fecha de Reserva");
        jLabelFecha.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N

        jLabelHoraInicio.setText("Hora Inicio");
        jLabelHoraInicio.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N

        jTextFieldMotivo.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N

        jLabelMotivo.setText("Motivo");
        jLabelMotivo.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N

        jLabelCubiculo.setText("Cubículo");
        jLabelCubiculo.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabelNumReservacion.setText("Numero Reservacion");
        jLabelNumReservacion.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N

        jTextFieldNumReservacion.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator2)
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnReagendar, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(290, 290, 290))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGap(398, 398, 398)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabelMotivo)
                                .addComponent(jLabelCubiculo))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTextFieldMotivo, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(309, 309, 309)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabelHoraInicio)
                                .addComponent(jLabelFecha))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(horaInicioPicker, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(fechaPicker, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 76, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(lblTitulo))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(265, 265, 265)
                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 543, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(274, 274, 274)
                        .addComponent(jLabelNumReservacion)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldNumReservacion, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(268, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitulo)
                .addGap(15, 15, 15)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 153, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNumReservacion)
                    .addComponent(jTextFieldNumReservacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelFecha)
                    .addComponent(fechaPicker, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(horaInicioPicker, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelHoraInicio))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldMotivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelMotivo))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCubiculo)
                    .addComponent(jComboBox1))
                .addGap(127, 127, 127)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnVolver, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnReagendar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        ControlNavegacion.volverPantallaAnterior();
    }//GEN-LAST:event_btnVolverActionPerformed

    private void btnReagendarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReagendarActionPerformed
        guardarReagenda();
    }//GEN-LAST:event_btnReagendarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnReagendar;
    private javax.swing.JButton btnVolver;
    private com.github.lgooddatepicker.components.DatePicker fechaPicker;
    private com.github.lgooddatepicker.components.TimePicker horaInicioPicker;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabelCubiculo;
    private javax.swing.JLabel jLabelFecha;
    private javax.swing.JLabel jLabelHoraInicio;
    private javax.swing.JLabel jLabelMotivo;
    private javax.swing.JLabel jLabelNumReservacion;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTextField jTextFieldMotivo;
    private javax.swing.JTextField jTextFieldNumReservacion;
    private javax.swing.JLabel lblTitulo;
    // End of variables declaration//GEN-END:variables
}
