/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pantallas;

import DTOs.ProductoMostrarDTO;
import DTOs.TarjetaDTO;
import gestion.IGestionPedidos;
import gestion.ManejadorPedidos;
import java.awt.*;
import javax.swing.*;

/**
 *
 * @author pablo
 */
public class PagoTarjeta extends javax.swing.JFrame {

    public static IGestionPedidos gestion = new ManejadorPedidos();

    /**
     * Creates new form PagoTarjeta
     */
    private TarjetaDTO tarjeta;

    public PagoTarjeta() {
        setTitle("Datos de la tarjeta");
        setSize(1000, 800);
        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationRelativeTo(null);

        // Panel Principal
        JPanel panelPrincipal = new JPanel(new BorderLayout(10, 10));

        // Título superior
        JLabel lblTitulo = new JLabel("Pago con tarjeta", SwingConstants.LEFT);
        lblTitulo.setForeground(Color.GRAY);
        lblTitulo.setFont(new Font("Arial", Font.BOLD, 14));
        JPanel panelTitulo = new JPanel(new BorderLayout());
        panelTitulo.add(lblTitulo, BorderLayout.WEST);
        panelTitulo.setBackground(Color.WHITE);

        // Panel de formulario
        JPanel panelFormulario = new JPanel(new GridLayout(4, 2, 10, 10));
        panelFormulario.setBackground(Color.LIGHT_GRAY);
        panelFormulario.setBorder(BorderFactory.createEmptyBorder(20, 20, 20, 20));

        panelFormulario.add(new JLabel("16 dígitos de la tarjeta"));
        JTextField txtNumero = new JTextField();
        panelFormulario.add(txtNumero);

        panelFormulario.add(new JLabel("Nombre de banco"));
        JTextField txtBanco = new JTextField();
        panelFormulario.add(txtBanco);

        panelFormulario.add(new JLabel("Fecha exp"));
        JTextField txtFecha = new JTextField();
        panelFormulario.add(txtFecha);

        panelFormulario.add(new JLabel("CVV"));
        JPasswordField txtCVV = new JPasswordField();
        panelFormulario.add(txtCVV);

        // Panel inferior con botones
        JPanel panelInferior = new JPanel(new BorderLayout());

        JButton btnAtras = new JButton("<-");
        btnAtras.setBackground(Color.GRAY);

        JButton btnConfirmar = new JButton("Confirmar pago");
        btnConfirmar.setBackground(Color.GRAY);

        panelInferior.add(btnAtras, BorderLayout.WEST);
        panelInferior.add(btnConfirmar, BorderLayout.EAST);

        btnAtras.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnAtrasSeleccionado();
            }
        });
        btnConfirmar.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnConfirmarSeleccionado(txtNumero, txtBanco, txtFecha, txtCVV);
            }
        });
        // Agregar componentes al JFrame
        panelPrincipal.add(panelTitulo, BorderLayout.NORTH);
        panelPrincipal.add(panelFormulario, BorderLayout.CENTER);
        panelPrincipal.add(panelInferior, BorderLayout.SOUTH);

        setContentPane(panelPrincipal);
    }

    public void BtnAtrasSeleccionado() {
        System.out.println("Regresa a pantalla anterior");
        dispose();
    }

    public void BtnConfirmarSeleccionado(JTextField txtNumero, JTextField txtBanco, JTextField txtFecha, JPasswordField txtCVV) {
        System.out.println("Confirmar tarjeta");
        TarjetaDTO tarjetaIngresada = new TarjetaDTO(
                txtNumero.getText(),
                txtBanco.getText(),
                txtFecha.getText(),
                new String(txtCVV.getPassword())
        );
        if (validarTarjetaPresentacion(tarjetaIngresada)) {
            JOptionPane.showMessageDialog(this, "Pago realizado con éxito", "Éxito", JOptionPane.INFORMATION_MESSAGE);            
        } else {
            JOptionPane.showMessageDialog(this, "Datos de la tarjeta inválidos", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    public boolean validarTarjetaPresentacion(TarjetaDTO tarjeta) {
        return gestion.validarTarjetaPresentacion(tarjeta);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
