/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package pantallas;

import DTOs.PedidoDTO;
import DTOs.PersistenciaProductoPedidoDTO;
import java.util.List;
import javax.swing.BoxLayout;

/**
 *
 * @author norma
 */
public class PanelPedidoIndividual extends javax.swing.JPanel {

    private List<PersistenciaProductoPedidoDTO> listaProductosPedidos;
    private PedidoDTO pedido;
    private PantallaEstadoPedidos pantallaPadre;

    public PanelPedidoIndividual(PedidoDTO pedido, PantallaEstadoPedidos pantallaPadre) {
        initComponents();
        this.pedido = pedido;
        this.pantallaPadre = pantallaPadre;
        this.listaProductosPedidos = pedido.getPedido();
        pnlProductosPedidos.setLayout(new BoxLayout(pnlProductosPedidos, BoxLayout.Y_AXIS));
        cargarInformacion();
    }

    public void cargarInformacion() {
        lblNumeroPedido.setText(""); //???

        pnlProductosPedidos.removeAll();

        for (PersistenciaProductoPedidoDTO productoPedido : listaProductosPedidos) {
            PanelPedidoIndividualProductosPedido panelProductoPedido = new PanelPedidoIndividualProductosPedido(productoPedido);
            pnlProductosPedidos.add(panelProductoPedido);
        }

        lblPrecioTotal.setText(String.format("$%.2f", pedido.getCostoTotal()));

        pnlProductosPedidos.revalidate();
        pnlProductosPedidos.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnTerminar = new javax.swing.JButton();
        lblPedido = new javax.swing.JLabel();
        lblTotal = new javax.swing.JLabel();
        pnlProductosPedidos = new javax.swing.JPanel();
        lblNumeroPedido = new javax.swing.JLabel();
        lblPrecioTotal = new javax.swing.JLabel();
        lblProductos = new javax.swing.JLabel();

        btnTerminar.setBackground(new java.awt.Color(255, 153, 0));
        btnTerminar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnTerminar.setForeground(new java.awt.Color(255, 255, 255));
        btnTerminar.setText("Terminar");
        btnTerminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTerminarActionPerformed(evt);
            }
        });

        lblPedido.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblPedido.setForeground(new java.awt.Color(255, 153, 0));
        lblPedido.setText("Pedido: ");

        lblTotal.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblTotal.setText("Total: ");

        javax.swing.GroupLayout pnlProductosPedidosLayout = new javax.swing.GroupLayout(pnlProductosPedidos);
        pnlProductosPedidos.setLayout(pnlProductosPedidosLayout);
        pnlProductosPedidosLayout.setHorizontalGroup(
            pnlProductosPedidosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 429, Short.MAX_VALUE)
        );
        pnlProductosPedidosLayout.setVerticalGroup(
            pnlProductosPedidosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 144, Short.MAX_VALUE)
        );

        lblNumeroPedido.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblNumeroPedido.setText("1");

        lblPrecioTotal.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblPrecioTotal.setText("$100");

        lblProductos.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblProductos.setText("Productos:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(18, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(lblTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblPrecioTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(pnlProductosPedidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblProductos, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblPedido)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblNumeroPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(btnTerminar, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTerminar)
                    .addComponent(lblPedido)
                    .addComponent(lblNumeroPedido))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblProductos)
                .addGap(7, 7, 7)
                .addComponent(pnlProductosPedidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTotal)
                    .addComponent(lblPrecioTotal))
                .addContainerGap(8, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnTerminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTerminarActionPerformed
//        pantallaPadre.recargarPaneles();
    }//GEN-LAST:event_btnTerminarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnTerminar;
    private javax.swing.JLabel lblNumeroPedido;
    private javax.swing.JLabel lblPedido;
    private javax.swing.JLabel lblPrecioTotal;
    private javax.swing.JLabel lblProductos;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JPanel pnlProductosPedidos;
    // End of variables declaration//GEN-END:variables
}
