/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package pantallas;

import DTOs.ProductoPedidoDTO;

/**
 *
 * @author norma
 */
public class PanelProductoPedido extends javax.swing.JPanel {

    /**
     * Creates new form PanelTotalDesglosado
     * @param productoPedido
     */
    public PanelProductoPedido(ProductoPedidoDTO productoPedido) {
        initComponents();
        this.lblNombreProducto.setText(productoPedido.getProducto().getNombre());
        this.lblTamaño.setText(productoPedido.getTamanio().getNombre());
        this.lblSabor.setText(productoPedido.getSabor().getNombre());
        double costo = productoPedido.getCosto();  
        this.lblPrecio.setText(String.format("%.2f", costo));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNombreProducto = new javax.swing.JLabel();
        lblTamaño = new javax.swing.JLabel();
        lblSabor = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        lblSigno = new javax.swing.JLabel();
        lblPrecio = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblNombreProducto.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblNombreProducto.setText("Producto");

        lblTamaño.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblTamaño.setText("Tamaño");

        lblSabor.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblSabor.setText("Sabor");

        jSeparator1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));

        lblSigno.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        lblSigno.setText("$");

        lblPrecio.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        lblPrecio.setText("Precio");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNombreProducto)
                    .addComponent(lblSabor)
                    .addComponent(lblTamaño))
                .addGap(99, 99, 99)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addComponent(lblSigno)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblPrecio)
                .addContainerGap(32, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(lblNombreProducto)
                        .addGap(32, 32, 32)
                        .addComponent(lblTamaño)
                        .addGap(26, 26, 26)
                        .addComponent(lblSabor))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblSigno)
                            .addComponent(lblPrecio))))
                .addContainerGap(52, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblNombreProducto;
    private javax.swing.JLabel lblPrecio;
    private javax.swing.JLabel lblSabor;
    private javax.swing.JLabel lblSigno;
    private javax.swing.JLabel lblTamaño;
    // End of variables declaration//GEN-END:variables
}
