/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pantallas;

import DTOs.ProductoPedidoDTO;
import control.ControlNavegacion;
import control.Modo;
import java.awt.BorderLayout;
import java.awt.Dimension;
import java.awt.FlowLayout;
import java.awt.Font;
import java.awt.GridLayout;
import javax.swing.BorderFactory;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JPanel;

/**
 * Clase que representa la pantalla para editar un producto dentro de un pedido.
 *
 * @author katia
 */
public class PantallaEditarProducto extends javax.swing.JFrame {

    private JButton btnProducto, btnTamanio, btnSabor, btnToppings, btnRegresar;

    /**
     * Constructor de la clase PantallaEditarProducto. Inicializa la ventana con
     * los datos del producto a editar.
     *
     * @param productoPedido Objeto ProductoPedidoDTO con la información del
     * producto actual.
     */
    public PantallaEditarProducto(ProductoPedidoDTO productoPedido) {
        ControlNavegacion.setProductoPedidoActual(productoPedido);
        setTitle("Editar Producto");
        setSize(1000, 800);
        setLayout(new BorderLayout());
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);

        JPanel panelBotones = new JPanel(new GridLayout(2, 2, 20, 20));
        panelBotones.setBorder(BorderFactory.createEmptyBorder(50, 50, 50, 50));

        btnProducto = new JButton("Producto: " + productoPedido.getProducto().getNombre());
        btnTamanio = new JButton("Tamaño: " + productoPedido.getTamanio().getNombre());
        btnSabor = new JButton("Sabor: " + productoPedido.getSabor().getNombre());
        if (productoPedido.getTopping() != null) {
            btnToppings = new JButton("Toppings: " + productoPedido.getTopping().getNombre());
        } else {
            btnToppings = new JButton("Toppings: Ninguno");
        }

        JButton[] botones = {btnProducto, btnTamanio, btnSabor, btnToppings};

        for (JButton boton : botones) {
            boton.setPreferredSize(new Dimension(250, 50));
            boton.setFont(new Font("Arial", Font.BOLD, 16));
        }

        btnRegresar = new JButton("←");
        btnRegresar.setPreferredSize(new Dimension(80, 40));
        panelBotones.add(btnProducto);
        panelBotones.add(btnTamanio);
        panelBotones.add(btnSabor);
        panelBotones.add(btnToppings);

        JPanel panelInferior = new JPanel(new FlowLayout(FlowLayout.LEFT));
        panelInferior.add(btnRegresar);

        btnProducto.addActionListener(e -> abrirProductos());
        btnTamanio.addActionListener(e -> abrirTamanios());
        btnSabor.addActionListener(e -> abrirSabores());
        btnToppings.addActionListener(e -> abrirToppings());
        btnRegresar.addActionListener(e -> regresar());

        // Agregar los paneles al Frame
        add(panelBotones, BorderLayout.CENTER);
        add(panelInferior, BorderLayout.SOUTH);

        setLocationRelativeTo(null);
        setVisible(true);
    }

    /**
     * Abre la pantalla de selección de productos en modo edición.
     */
    private void abrirProductos() {
        dispose(); // Cierra la pantalla actual antes de abrir la nueva
        ControlNavegacion.mostrarPantallaProductos(Modo.EDICION);
    }

    /**
     * Abre la pantalla de selección de tamaños en modo edición.
     */
    private void abrirTamanios() {
        dispose();
        ControlNavegacion.mostrarPantallaTamanios(Modo.EDICION);
    }

    /**
     * Abre la pantalla de selección de sabores en modo edición.
     */
    private void abrirSabores() {
        dispose();
        ControlNavegacion.mostrarPantallaSabores(Modo.EDICION);
    }

    /**
     * Abre la pantalla de selección de toppings en modo edición.
     */
    private void abrirToppings() {
        dispose();
        ControlNavegacion.mostrarPantallaToppings(Modo.EDICION);
    }

    /**
     * Regresa a la pantalla de total desglosado tras calcular costos y
     * actualizar el producto pedido.
     */
    private void regresar() {
        ControlNavegacion.calcularCosto();
        ControlNavegacion.crearProductoPedido();
        this.dispose();
        ControlNavegacion.mostrarPantallaTotalDesglosado();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
