/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pantallas;

import DTOs.PedidoDTO;
import control.ControlNavegacion;
import java.awt.Component;
import java.util.List;
import javax.swing.BoxLayout;
import javax.swing.JLabel;
import javax.swing.JPanel;

/**
 *
 * @author norma
 */
public class PantallaEstadoPedidos extends javax.swing.JFrame {

    private final int MOVIMIENTO_SCROLL_MOUSE = 15;
    private JPanel contenedorPaneles;
     private List<PedidoDTO> pedidos;

    public PantallaEstadoPedidos() {
        initComponents();
        ajustarScroll();
        cargarPanelesPedidos();
    }

    private void ajustarScroll() {
        if (scrollPane != null && scrollPane.getVerticalScrollBar() != null) {
            scrollPane.getVerticalScrollBar().setUnitIncrement(MOVIMIENTO_SCROLL_MOUSE);
        }
    }

    private void cargarPanelesPedidos() {
        this.pedidos = ControlNavegacion.obtenerPedidosDelivery();
        int posicionScroll = scrollPane.getVerticalScrollBar().getValue();
        JPanel contenedorPanel = obtenerPaneles(pedidos);
        scrollPane.setViewportView(contenedorPanel);
        scrollPane.getVerticalScrollBar().setValue(posicionScroll);
    }

    private JPanel obtenerPaneles(List<PedidoDTO> pedidos) {
        contenedorPaneles = new JPanel();
        contenedorPaneles.setLayout(new BoxLayout(contenedorPaneles, BoxLayout.Y_AXIS));

        if (pedidos == null || pedidos.isEmpty()) {
            JLabel lblVacio = new JLabel("No hay pedidos pendientes actualmente.");
            lblVacio.setAlignmentX(Component.CENTER_ALIGNMENT);
            contenedorPaneles.add(lblVacio);
            return contenedorPaneles;
        }

        for (PedidoDTO pedido : pedidos) {
            PanelPedidoIndividual panelPedidoIndividual = new PanelPedidoIndividual(pedido, this);
            contenedorPaneles.add(panelPedidoIndividual);

        }
        return contenedorPaneles;
    }
    
    public JPanel getContenedorPaneles() {
        return contenedorPaneles;
    }

    /**
     * Acción q: Recarga los paneles de comandas, obteniendo la lista
     * actualizada de comandas registradas desde el controlador de navegación.
     * Refresca la interfaz gráfica para mostrar los datos más recientes.
     */
    public void recargarPaneles() {
        this.pedidos = ControlNavegacion.obtenerPedidosDelivery();
        cargarPanelesPedidos();
        this.revalidate();
        this.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sepArriba = new javax.swing.JSeparator();
        lblTitulo = new javax.swing.JLabel();
        btnVolverAtras = new javax.swing.JButton();
        scrollPane = new javax.swing.JScrollPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTitulo.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lblTitulo.setText("Estado de pedidos");
        lblTitulo.setToolTipText("");

        btnVolverAtras.setBackground(new java.awt.Color(255, 204, 0));
        btnVolverAtras.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnVolverAtras.setText("<---");
        btnVolverAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverAtrasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sepArriba, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 507, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(64, Short.MAX_VALUE)
                .addComponent(scrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 757, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnVolverAtras, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(lblTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sepArriba, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(scrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addComponent(btnVolverAtras, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVolverAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverAtrasActionPerformed
        ControlNavegacion.mostrarPantallaMenuIniciado();
        this.dispose();
    }//GEN-LAST:event_btnVolverAtrasActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnVolverAtras;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JScrollPane scrollPane;
    private javax.swing.JSeparator sepArriba;
    // End of variables declaration//GEN-END:variables
}
