/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pantallas;

import DTOs.TamanioMostrarDTO;
import control.ControlNavegacion;
import control.Modo;
import exception.GestionException;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Cursor;
import java.awt.GridLayout;
import java.awt.event.MouseAdapter;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BorderFactory;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.SwingConstants;

/**
 * Clase que representa la pantalla de selección de tamaños.
 *
 * @author rodri
 */
public class PantallaTamanios extends javax.swing.JFrame {

    private final int COLUMNAS_TABLA_TAMANIOS = 3;
    private final int PADDING_HORIZONTAL = 10;
    private final int PADDING_VERTICAL = 10;
    private final Color COLOR_HOVER_PANEL = new Color(220, 220, 220);
    List<TamanioMostrarDTO> tamanios;
    private Modo modo;
    private JPanel panelConTodosLosTamanios;

    /**
     * Constructor de la clase PantallaTamanios. Crea una nueva pantalla para la
     * selección de tamaños.
     *
     * @param tamanios Lista de tamaños disponibles para mostrar.
     * @param modo Modo en el que se abrirá la pantalla (CREACION o EDICION).
     */
    public PantallaTamanios(List<TamanioMostrarDTO> tamanios, Modo modo) {
        this.tamanios = tamanios;
        this.modo = modo;
        initComponents2();
        setTitle("Tamaños");
        setSize(1000, 800);
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        agregarTamanios();
    }

    /**
     * Agrega los tamaños disponibles al panel de selección. Se crean paneles
     * individuales para cada tamaño con eventos de interacción.
     */
    private void agregarTamanios() {
        for (TamanioMostrarDTO tamanio : tamanios) {
            JPanel panelTamanio = new PanelTamanio(tamanio);
            panelTamanio.addMouseListener(new EventosPanelTamanio(tamanio, panelTamanio));
            panelConTodosLosTamanios.add(panelTamanio);
        }
        panelConTodosLosTamanios.revalidate();
        panelConTodosLosTamanios.repaint();
    }

    /**
     * Maneja la selección de un tamaño y redirige a la siguiente pantalla
     * dependiendo del modo en que se encuentre la aplicación.
     *
     * @param tamanio El tamaño seleccionado.
     */
    private void tamanioSeleccionado(TamanioMostrarDTO tamanio) {
        ControlNavegacion.agregarTamanio(tamanio);
        if (modo == Modo.CREACION) {
            try {
                ControlNavegacion.mostrarPantallaSabores(Modo.CREACION);
            } catch (GestionException ex) {
                Logger.getLogger(PantallaTamanios.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else if (modo == Modo.EDICION) {
            ControlNavegacion.mostrarPantallaEditarProducto(ControlNavegacion.getProductoPedidoActual());
        }
        this.dispose();
    }

    /**
     * Clase interna que maneja los eventos de los paneles de tamaño.
     */
    private class EventosPanelTamanio extends MouseAdapter {

        private final TamanioMostrarDTO tamanio;
        private final JPanel panel;

        /**
         * Constructor de la clase de eventos del panel de tamaño.
         *
         * @param tamanio Tamaño asociado al panel.
         * @param panel Panel que representa el tamaño.
         */
        public EventosPanelTamanio(TamanioMostrarDTO tamanio, JPanel panel) {
            this.tamanio = tamanio;
            this.panel = panel;
        }

        @Override
        public void mousePressed(java.awt.event.MouseEvent evt) {
            tamanioSeleccionado(tamanio);
        }

        @Override
        public void mouseEntered(java.awt.event.MouseEvent evt) {
            panel.setCursor(new Cursor(Cursor.HAND_CURSOR));
            panel.setBackground(COLOR_HOVER_PANEL);
        }

        @Override
        public void mouseExited(java.awt.event.MouseEvent evt) {
            panel.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
            panel.setBackground(null);
        }
    }

    /**
     * Regresa a la pantalla anterior dependiendo del modo actual.
     */
    private void regresar() {
        if (modo == Modo.CREACION) {
            ControlNavegacion.volverPantallaAnterior();
        } else if (modo == Modo.EDICION) {
            ControlNavegacion.mostrarPantallaEditarProducto(ControlNavegacion.getProductoPedidoActual());
            this.dispose();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 870, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 493, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(100, 100, 100))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(200, 200, 200)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(200, 200, 200))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
    /**
     * Método para inicializar componentes personalizados. Configura la
     * estructura y apariencia de la pantalla.
     */
    private void initComponents2() {
        setTitle("Tamaños");
        setSize(1000, 800);
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setLayout(new BorderLayout());

        JLabel lblTitulo = new JLabel("Selecciona un tamaño", SwingConstants.LEFT);
        lblTitulo.setFont(new java.awt.Font("Segoe UI", 0, 48));
        lblTitulo.setBorder(BorderFactory.createEmptyBorder(10, 10, 10, 10));
        add(lblTitulo, BorderLayout.NORTH);

        panelConTodosLosTamanios = new JPanel();
        panelConTodosLosTamanios.setLayout(new GridLayout(0, COLUMNAS_TABLA_TAMANIOS, PADDING_HORIZONTAL, PADDING_VERTICAL));
        add(new JScrollPane(panelConTodosLosTamanios), BorderLayout.CENTER);

        JPanel panelNavegacion = new JPanel(new BorderLayout());
        JButton btnRegresar = new JButton();
        btnRegresar.setBackground(new java.awt.Color(255, 255, 51));
        btnRegresar.setFont(new java.awt.Font("Segoe UI", 0, 48));
        btnRegresar.setText("<---");
        btnRegresar.setPreferredSize(new java.awt.Dimension(180, 70));
        btnRegresar.addActionListener(e -> regresar());

        panelNavegacion.add(btnRegresar, BorderLayout.WEST);
        add(panelNavegacion, BorderLayout.SOUTH);
    }

}
