/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pantallas;

import DTOs.ProductoMostrarDTO;
import control.ControlNavegacion;
import java.awt.*;
import java.util.List;
import javax.swing.*;

/**
 *
 * @author Jp
 */
public class Productos extends javax.swing.JFrame {

    /**
     * Creates new form Productos
     */
    List<ProductoMostrarDTO> productos;
    
    private EditarProducto editarProductoFrame;

    public Productos(List<ProductoMostrarDTO> productos) {
        this.productos = productos;
        initComponents();
        agregarProductos();
        ajustarScroll();
    }
    
    public Productos(List<ProductoMostrarDTO> productos, EditarProducto editarProductoFrame) {
        this.editarProductoFrame = editarProductoFrame;
        this.productos = productos;
        initComponents();
        agregarProductos();
        ajustarScroll();
    }
    
    private void ajustarScroll() {
        jScrollPane1.getVerticalScrollBar().setUnitIncrement(15);
    }
    
    private void agregarProductos() {
        int columnas = 3; // Número de productos por fila
        int filas = (int) Math.ceil((double) productos.size() / columnas); // Calcula filas necesarias

        jPanel1.setLayout(new GridLayout(filas, columnas, 10, 10)); // Espaciado entre productos

        for (ProductoMostrarDTO producto : productos) {
            JPanel panelProducto = new JPanel();
            panelProducto.setLayout(new BorderLayout());
            panelProducto.setBorder(BorderFactory.createLineBorder(Color.GRAY, 1));
            panelProducto.setPreferredSize(new Dimension(150, 150));

            // Cargar imagen desde la URL o ruta del sistema
            JLabel lblImagen = new JLabel();
            ImageIcon icono = new ImageIcon(producto.getUrlImagen());
            Image img = icono.getImage().getScaledInstance(100, 100, Image.SCALE_SMOOTH);
            lblImagen.setIcon(new ImageIcon(img));
            lblImagen.setHorizontalAlignment(JLabel.CENTER);

            JLabel lblNombre = new JLabel(producto.getNombre(), SwingConstants.CENTER);

            panelProducto.add(lblImagen, BorderLayout.CENTER);
            panelProducto.add(lblNombre, BorderLayout.SOUTH);

            panelProducto.addMouseListener(new java.awt.event.MouseAdapter() {
                @Override
                public void mousePressed(java.awt.event.MouseEvent evt) {
                    productoSeleccionado(producto); // Método que recibe el ProductoMostrarDTO
                }

                @Override
                public void mouseEntered(java.awt.event.MouseEvent evt) {
                    panelProducto.setCursor(new Cursor(Cursor.HAND_CURSOR));
                    panelProducto.setBackground(new Color(220, 220, 220));
                }

                @Override
                public void mouseExited(java.awt.event.MouseEvent evt) {
                    panelProducto.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
                    panelProducto.setBackground(null);
                }
            });

            jPanel1.add(panelProducto);
        }

        jPanel1.revalidate();
        jPanel1.repaint();
    }

    private void productoSeleccionado(ProductoMostrarDTO producto) {
        if (editarProductoFrame != null){
            editarProductoFrame.actualizarProducto(producto);
            editarProductoFrame.setVisible(true);
        } else{
            ControlNavegacion.mostrarPantallaTamanios();
        }
        ControlNavegacion.gestor.agregarProducto(producto);
        //
         System.out.println(ControlNavegacion.gestor.getProductoPedido());
         System.out.println(ControlNavegacion.gestor.getPedido());
         
        //
        this.dispose();
    }
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Productos");
        setResizable(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1010, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 522, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(jPanel1);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jLabel1.setText("Selecciona tu producto");

        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jButton1.setText("<---");
        jButton1.setMaximumSize(new java.awt.Dimension(120, 70));
        jButton1.setMinimumSize(new java.awt.Dimension(120, 70));
        jButton1.setPreferredSize(new java.awt.Dimension(120, 70));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addComponent(jSeparator2)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1)
                .addGap(18, 18, 18)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        ControlNavegacion.volverPantallaAnterior();
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    // End of variables declaration//GEN-END:variables
}
