/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pantallas;

import DTOs.SaboresMostrarDTO;
import control.ControlNavegacion;
import control.Modo;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.GridLayout;
import java.awt.Image;
import java.util.List;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.SwingConstants;

/**
 *
 * @author rodri
 */
public class Sabores extends javax.swing.JFrame {

    List<SaboresMostrarDTO> sabores;
    private Modo modo;
    private PantallaEditarProducto editarProductoFrame;

    /**
     * Creates new form Sabores
     */

    public Sabores(List<SaboresMostrarDTO> sabores) {
        this.sabores = sabores;
        initComponents();
        setTitle("Sabores");
        setSize(1000, 800);
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        agregarSabores();

    }

    public Sabores(List<SaboresMostrarDTO> sabores, PantallaEditarProducto editarProductoFrame) {
        this.sabores = sabores;
        this.editarProductoFrame = editarProductoFrame;
        initComponents();
        setTitle("Sabores");
        setSize(1024, 768);
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        agregarSabores();

    }

    private void agregarSabores() {
        int columnas = 3; // Número de productos por fila
        int filas = (int) Math.ceil((double) sabores.size() / columnas); // Calcula filas necesarias

        jPanel1.setLayout(new GridLayout(filas, columnas, 10, 10)); // Espaciado entre productos

        for (SaboresMostrarDTO sabor : sabores) {
            JPanel panelTamanio = new JPanel();
            panelTamanio.setLayout(new BorderLayout());
            panelTamanio.setBorder(BorderFactory.createLineBorder(Color.GRAY, 1));

            // Cargar imagen desde la URL o ruta del sistema
            JLabel lblImagen = new JLabel();
            ImageIcon icono = new ImageIcon(sabor.getUrlImagen());
            Image img = icono.getImage().getScaledInstance(150, 150, Image.SCALE_SMOOTH);
            lblImagen.setIcon(new ImageIcon(img));
            lblImagen.setHorizontalAlignment(JLabel.CENTER);

            JLabel lblNombre = new JLabel(sabor.getNombre(), SwingConstants.CENTER);

            panelTamanio.add(lblImagen, BorderLayout.CENTER);
            panelTamanio.add(lblNombre, BorderLayout.SOUTH);

            panelTamanio.addMouseListener(new java.awt.event.MouseAdapter() {
                public void mouseClicked(java.awt.event.MouseEvent evt) {
                    saborSeleccionado(sabor); // Método que recibe el ProductoMostrarDTO
                }
            });

            jPanel1.add(panelTamanio);

        }

        jPanel1.revalidate();
        jPanel1.repaint();
    }

    private void saborSeleccionado(SaboresMostrarDTO sabor) {

        ControlNavegacion.gestor.agregarSabor(sabor);
        ControlNavegacion.mostrarPantallaToppings(Modo.CREACION);

        dispose();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        presentacion1 = new com.mycompany.presentacion.Presentacion();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1058, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 493, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(200, 200, 200)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(200, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private com.mycompany.presentacion.Presentacion presentacion1;
    // End of variables declaration//GEN-END:variables
}
