/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pantallas;

import DTOs.ToppingsMostrarDTO;
import control.ControlNavegacion;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.GridLayout;
import java.awt.Image;
import java.util.List;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.SwingConstants;

/**
 *
 * @author katia
 */
public class Toppings extends javax.swing.JFrame {

    List<ToppingsMostrarDTO> toppings;
    private EditarProducto editarProductoFrame;
    private JPanel panelConTodosLosToppings;

    
    /**
     * Creates new form Toppings
     */
    public Toppings(List<ToppingsMostrarDTO> toppings) {
        this.toppings = toppings;
        initComponents2();
        setTitle("Toppings");
        setSize(1024, 768);
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        agregarToppings();
    }
    
    public Toppings(List<ToppingsMostrarDTO> toppings, EditarProducto editarProductoFrame) {
        this.toppings = toppings;
        this.editarProductoFrame = editarProductoFrame;
        initComponents2();
        agregarToppings();
    }
    
    private void initComponents2(){
        setTitle("Toppings");
        setSize(1000, 800);
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setLayout(new BorderLayout());
        
        JLabel lblTitulo = new JLabel("Toppings", SwingConstants.CENTER);
        lblTitulo.setFont(new Font("Arial", Font.BOLD, 24));
        lblTitulo.setBorder(BorderFactory.createEmptyBorder(10, 10, 10, 10));
        add(lblTitulo, BorderLayout.NORTH);
        
        panelConTodosLosToppings = new JPanel();
        panelConTodosLosToppings.setLayout(new GridLayout(0, 2, 20, 20));
        add(new JScrollPane(panelConTodosLosToppings), BorderLayout.CENTER);
        
        JPanel panelNavegacion = new JPanel(new BorderLayout());
        
        JButton btnRegresar = new JButton("<-");
        btnRegresar.setFont(new Font("Arial", Font.BOLD, 16));
        btnRegresar.addActionListener(e -> regresar());
        
        panelNavegacion.add(btnRegresar, BorderLayout.WEST);
        add(panelNavegacion,BorderLayout.SOUTH);
    }
    
        
    private void agregarToppings() {
        for (ToppingsMostrarDTO topping : toppings) {
            JPanel panelTopping = new JPanel(new BorderLayout());
            panelTopping.setBorder(BorderFactory.createLineBorder(Color.GRAY, 1));
            panelTopping.setPreferredSize(new Dimension(250, 300));

            JLabel lblImagen = new JLabel();
            ImageIcon icono = new ImageIcon(topping.getUrlImagen());
            Image img = icono.getImage().getScaledInstance(250, 250, Image.SCALE_SMOOTH);
            lblImagen.setIcon(new ImageIcon(img));
            lblImagen.setHorizontalAlignment(JLabel.CENTER);

            JLabel lblNombre = new JLabel(topping.getNombre(), SwingConstants.CENTER);
            lblNombre.setFont(new Font("Arial", Font.BOLD, 16));
            
            panelTopping.add(lblImagen, BorderLayout.CENTER);
            panelTopping.add(lblNombre, BorderLayout.SOUTH);

            panelTopping.addMouseListener(new java.awt.event.MouseAdapter() {
                public void mouseClicked(java.awt.event.MouseEvent evt) {
                    toppingSeleccionado(topping); 
                }
            });

            panelConTodosLosToppings.add(panelTopping);
        }

        panelConTodosLosToppings.revalidate();
        panelConTodosLosToppings.repaint();
    }
    
    
    
    private void toppingSeleccionado(ToppingsMostrarDTO topping){
        if (editarProductoFrame != null){
            editarProductoFrame.actualizarTopping(topping);
            editarProductoFrame.setVisible(true);
        } else{
            ControlNavegacion.mostrarAgregarTerminarPedido();
        }
        ControlNavegacion.gestor.agregarTopping(topping);
        this.dispose();
    }
    
    private void regresar(){
        ControlNavegacion.volverPantallaAnterior();
    }
        
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 345, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 245, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents



    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
